version: '3'

networks:
  internal_network:
    driver: bridge

volumes:
  mysql_volume: { }

services:
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=P@ssw0rd123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=P@ssw0rd123
    networks:
      - internal_network
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker-script/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
